baseurl = "http://darupants.github.io/"
languageCode = "ja"
title = "Darudaru Blog"
theme = "hugo-zen"
author = "darupants"
copyright = "darupants All rights reserved."


[params]
  logo      = "/images/darupants.jpg"
  twitter   = "https://twitter.com/darupants"
  github    = "https://github.com/darupants/"
  email     = "darupants@gmail.com"
